name: fullstack_flutter_salesbet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
   # --- AUTHENTICATION ---
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  github_sign_in_plus: ^0.0.2
  pin_code_fields: ^8.0.1
  # flutter_facebook_auth: ^6.0.4

  # --- STORAGE ---
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.1
  firebase_app_check: ^0.3.2+9
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1

  # --- FILES / MEDIA ---
  image_picker: ^1.1.2
  file_picker: ^10.2.0

  # --- UTILITIES ---
  http: ^0.13.5
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  intl: ^0.20.2
  logger: ^2.4.0
  flutter_local_notifications: ^18.0.0
  url_launcher: ^6.3.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^6.0.5
  status_alert: ^1.0.1
  flutter_animated_icons: ^1.0.1
  form_validator: ^2.1.1
  smooth_page_indicator: ^1.2.0+3
  go_router: ^16.1.0
  google_maps_flutter: ^2.9.0
  percent_indicator: ^4.2.5
  local_auth: ^2.3.0
  uuid: ^4.5.0
  wakelock_plus: ^1.3.2
  permission_handler: ^12.0.0+1
  timezone: ^0.9.4

  # --- UI / ICONS ---
  sign_button: ^2.0.6
  carousel_slider: ^5.0.0
  fl_chart: ^1.0.0
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1

  # --- STATE MANAGEMENT ---
  flutter_riverpod: ^2.5.1
  get: ^4.6.6

  # --- REALTIME / WEBSOCKETS ---
  socket_io_client: ^3.1.2

  # --- TOASTS / ALERTS ---
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
