// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSdbic5k_LqNwN5EDy0gJJOPkOKSIcV0',
    appId: '1:132247431010:web:d3c346d67204f8beb2ee3b',
    messagingSenderId: '132247431010',
    projectId: 'fullstack-flutter-salesbet',
    authDomain: 'fullstack-flutter-salesbet.firebaseapp.com',
    storageBucket: 'fullstack-flutter-salesbet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmjc5sL8A1vDl8Ex5SIrn_T-YYJi5NsME',
    appId: '1:132247431010:android:0089b23c59bcd731b2ee3b',
    messagingSenderId: '132247431010',
    projectId: 'fullstack-flutter-salesbet',
    storageBucket: 'fullstack-flutter-salesbet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJvhV5or2aeUqYUJTRI0pPrHBEX59dbQ',
    appId: '1:132247431010:ios:7bd3a696d4ca9c98b2ee3b',
    messagingSenderId: '132247431010',
    projectId: 'fullstack-flutter-salesbet',
    storageBucket: 'fullstack-flutter-salesbet.firebasestorage.app',
    iosBundleId: 'com.example.fullstackFlutterSalesbet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJvhV5or2aeUqYUJTRI0pPrHBEX59dbQ',
    appId: '1:132247431010:ios:7bd3a696d4ca9c98b2ee3b',
    messagingSenderId: '132247431010',
    projectId: 'fullstack-flutter-salesbet',
    storageBucket: 'fullstack-flutter-salesbet.firebasestorage.app',
    iosBundleId: 'com.example.fullstackFlutterSalesbet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRSdbic5k_LqNwN5EDy0gJJOPkOKSIcV0',
    appId: '1:132247431010:web:dd74c9c1f491d46eb2ee3b',
    messagingSenderId: '132247431010',
    projectId: 'fullstack-flutter-salesbet',
    authDomain: 'fullstack-flutter-salesbet.firebaseapp.com',
    storageBucket: 'fullstack-flutter-salesbet.firebasestorage.app',
  );
}
